# Generated by Django 5.2.7 on 2025-11-22 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_bus_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuprequest',
            name='cleared_by_driver',
            field=models.BooleanField(default=False),
        ),
    ]
